### ISSUE TITLE
Cannot read property 'Resources' of undefined

### ISSUE THREAD

**Issue by huksley** [neverendingqs/serverless-default-aws-resource-properties#17]
Hello,

I am using `"serverless-default-aws-resource-properties": "0.0.15"` and `"serverless": "^1.78.1"`
and getting following error when trying to deploy:
```
  TypeError: Cannot read property 'Resources' of undefined
      at DefaultAwsProperties.addDefaults (/Users/ruslan/src/myproject/node_modules/serverless-default-aws-resource-properties/index.js:35:49)
```

this line contains: 
```
const resources = this.serverless.resources.Resources;
```

I also use a bunch of other plugins, if it is matter.

**Comment by neverendingqs** [comment]
Thanks for reporting. Do you have a sample `serverless.yml` file you can share that reproduces this issue?

**Comment by huksley** [comment]
@neverendingqs Here is the example app which inhibits this behaviour https://github.com/huksley/serverless-default-aws-resource-properties-example

**Comment by huksley** [comment]
nvm https://github.com/huksley/serverless-s3-block-public-access

**Comment by mars-lan** [comment]
Seems like the plugin expects there to be a `resources` key in `serverless.yml` so a workaround is to an empty key like this

```
# serverless.yaml
...
functions: 
  ...
resources:
  Resources:
```

@neverendingqs could you reopen this issue and handle the case of missing `resources` key gracefully?

**Comment by mars-lan** [comment]
Actually never mind. Seems like this plugin only deal with custom resources. For the default s3 bucket created by serverless framework, simply set the following

```
# serverless.yaml
provider: 
  deploymentBucket:
    blockPublicAccess: true 
```

**Comment by neverendingqs** [comment]
Hmmm that's interesting. It's possible to deal with all resources, but that might be viewed as unexpected behaviour in other scenarios.
